repo_path="/home/manick/devopsAssasination/assig2-gitData/repo"
dataViz_repo_path="/home/manick/devopsAssasination/assig2-gitData/repo/dataViz/data-visualization"
mm16_repo_path="/home/manick/devopsAssasination/assig2-gitData/repo/mm16/moderndatabases-monsoon16"
sap_repo_path="/home/manick/devopsAssasination/assig2-gitData/repo/sap/sap-efrei-spring-2016"
dataViz_output_file="/home/manick/devopsAssasination/assig2-gitData/data/dataViz_log.txt"
mm16_output_file="/home/manick/devopsAssasination/assig2-gitData/data/mm16_log.txt"
sap_output_file="/home/manick/devopsAssasination/assig2-gitData/data/sap_log.txt"
